checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'var/*'
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'vendor/*'
        - '*.min.js'
build:
    tests:
        override:
            -
                command: './vendor/bin/simple-phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
