language: php

# Some code courtesy of the mediawiki-api contributors, released under GPL-2.0
# https://github.com/addwiki/mediawiki-api-base/blob/master/build/travis/install-mediawiki.sh

# list any PHP version you want to test against
php:
    # using major version aliases
    # aliased to a recent 5.6.x version
    - 5.6
    # aliased to a recent 7.x version
    - 7.1

env:
  - MW=REL1_30

addons:
    mariadb: '10.0'

services:
    - mysql

before_install:
    - bash ./build/travis/install-mediawiki.sh

install:
    - travis_retry composer install
    - wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar

before_script:
    # Symfony database
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - php bin/console doctrine:database:create --env=test --no-interaction --quiet
    - php bin/console doctrine:migrations:migrate --env=test --no-interaction --quiet

    # MediaWiki
    - bash ./build/travis/run-webserver.sh
    - export MW_API='http://localhost:8080/w/api.php'
    - export MW_USER='CIUser'
    - export MW_PASSWORD='CIPass'

script:
    - composer validate
    - ./vendor/bin/phpcs -s .
    - php phpDocumentor.phar -d src --template="checkstyle"
    - ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml

after_success:
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
    directories:
        - $HOME/.composer/cache

sudo: false
