language: php

# list any PHP version you want to test against
php:
    # using major version aliases
    # aliased to a recent 5.6.x version
    - 5.6
    # aliased to a recent 7.x version
    - 7.0

install:
    - composer install
    - wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor.phar

script:
    - composer validate
    - ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml
    - ./vendor/bin/phpcs -s .
    - php phpDocumentor.phar -d src --template="checkstyle"

sudo: false
