imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: random_background.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']

# CSS preprocessing
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            apply_to:  '\.scss$'
        cssrewrite: ~
    assets:
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js
        jquery_i18n:
            inputs:
                - %kernel.root_dir%/../app/Resources/assets/js/jquery.i18n.dist.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
            output: "fonts/glyphicons-halflings-regular.woff2"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        opensans_ttf:
            inputs:
                - %kernel.root_dir%/../app/Resources/fonts/OpenSans-Regular.ttf
            output: "fonts/OpenSans-Regular.ttf"
        fontawesome_ttf:
            inputs:
                - %kernel.root_dir%/../app/Resources/fonts/fontawesome-webfont.ttf
            output: "fonts/fontawesome-webfont.ttf"

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            grantmetrics:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            centralauth:
                driver:   pdo_mysql
                host:     "%database_replica_host%"
                port:     "%database_replica_port%"
                dbname:   "centralauth_p"
                user:     "%database_replica_user%"
                password: "%database_replica_password%"
                charset:  UTF8
            replicas:
                driver:   pdo_mysql
                host:     "%database_replica_host%"
                port:     "%database_replica_port%"
                dbname:   "%database_replica_name%"
                user:     "%database_replica_user%"
                password: "%database_replica_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: grantmetrics
        entity_managers:
            grantmetrics:
                connection: grantmetrics
                mappings:
                    model:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/AppBundle/Model'
                        prefix: AppBundle\Model
                        alias: Model
                        is_bundle: false
            centralauth:
                connection: centralauth
                naming_strategy: doctrine.orm.naming_strategy.underscore
            replicas:
                connection: replicas
                naming_strategy: doctrine.orm.naming_strategy.underscore

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        commons:
            base_url: "https://commons.wikimedia.org/w/api.php"

            # guzzle client options (full description here: https://guzzle.readthedocs.org/en/latest/request-options.html)
            options:
                headers:
                    Accept: "application/json"
                timeout: 30
